<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>M_SPlaywrightBDD</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
		<PackageReference Include="Microsoft.Playwright.NUnit" Version="1.61.0" />
		<PackageReference Include="NUnit" Version="3.14.0" />
		<PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
		<PackageReference Include="Reqnroll" Version="3.3.4" />
		<PackageReference Include="Reqnroll.Assist.Dynamic" Version="3.3.4" />
		<PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
		<PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="3.3.4" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="ApplicationLayer\Models\" />
		<Folder Include="TestLayer\FeatureFiles\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="RunSettings\dev.runsettings">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>

		<None Update="RunSettings\tst.runsettings">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>

		<None Update="RunSettings\stg.runsettings">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>

		<None Update="RunSettings\uat.runsettings">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>

		<None Update="RunSettings\prod.runsettings">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>